[global_map]
clk = "clock"

[interface_map.fifo_in]
data_rdy = "data_in_rdy"
data_vld = "data_in_vld"
data = "data_in"

[interface_map.fifo_out]
data_vld = "data_out_vld"
data_rdy = "data_out_rdy"
data = "data_out"

