name = "fifo_out"
ports = [
  "data [31:0]",
  "data_vld",
  "data_rdy"
]
clock = "clk"

[item]
members = [
  "rand bit[31:0] data",
  "rand int delay"
]
constraints = [
  "delay inside {[1:100]}"
]

